<project>

  <target name="compile">
    <mkdir dir="classes"/>

    <javac srcdir="src"
	   destdir="classes"
	   includeantruntime="false"/>
  </target>
  
  <target name="run" depends="compile">
    <java classname="sicht.zwei.graph.Main"
	  classpath="classes"
	  fork="true"></java>
  </target>
  
</project>
